title: Minha página de anotações
description: Minhas notas e observações de estudo sobre Eletrônica Digital. Esta página está em constante evolução.
show_downloads: false
google_analytics:
theme: jekyll-theme-midnight
remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme
